name: e-commerce CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Install yarn
        run: sudo npm install -g yarn
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Build the dist
        run: yarn build
      - name: setup and restart service
        run: |
          sudo systemctl daemon-reload
          sudo systemctl start e-commerce-api
          sudo systemctl enable e-commerce-api
